import { useEffect, useRef, useState } from 'react'
import ReactMarkdown from 'react-markdown'
import rehypeSanitize from 'rehype-sanitize'
import remarkGfm from 'remark-gfm'
import type { Components } from 'react-markdown'
import type { ContentDocument } from '../content'
import { resolveContentUrl } from '../lib/paths'

function splitHeadingBlocks(body: string) { const p = body.split(/^##\s+(.+)$/m); const blocks: Array<{ title: string; content: string }> = []; for (let i = 1; i < p.length; i += 2) blocks.push({ title: p[i].trim(), content: p[i + 1].trim() }); return { lead: p[0].trim(), blocks } }
const common: Components = { a: ({ href = '', children, ...props }) => <a href={resolveContentUrl(href)} {...(/^(https?:)/.test(href) ? { target: '_blank', rel: 'noreferrer' } : {})} {...props}>{children}</a>, img: ({ src = '', alt = '', ...props }) => <img alt={alt} src={resolveContentUrl(src)} {...props} /> }
function Markdown({ children, components }: { children: string; components?: Components }) { return <ReactMarkdown rehypePlugins={[rehypeSanitize]} remarkPlugins={[remarkGfm]} components={{ ...common, ...components }}>{children}</ReactMarkdown> }
function Steps({ children }: { children: React.ReactNode }) { return <ol className="voice-install-steps">{children}</ol> }

function Register({ document }: { document: ContentDocument }) {
  const { lead, blocks } = splitHeadingBlocks(document.body)
  const checks = ['已录入的舰长 UID', 'B 站 UID', 'Java 版游戏用户名', '单独设置的登录密码']
  const fields = [['游戏用户名', '填写你实际进入服务器时使用的用户名，务必保持一致。'], ['B 站 UID', '打开自己的 B 站个人主页即可查看，是一串数字。'], ['Java 版游戏用户名', '填写你实际进入服务器时使用的用户名，务必保持一致。'], ['单独设置的登录密码', '用于舰长服登录，不要使用微信、B 站账号密码。']]
  return <><Markdown components={{ p: ({ children }) => <p className="lead">{children}</p> }}>{lead}</Markdown><ul className="check-list">{checks.map((label, index) => <li key={label}><b>{label}</b><span>{blocks[0]?.content.split(/\r?\n/).filter((line) => line.startsWith('-'))[index]?.replace(/^-\s*(?:\*\*)?[^：:]+(?:\*\*)?[：:]/, '').trim() || ''}</span></li>)}</ul><div className="subsection-heading"><span>REGISTRATION</span><h3>填写注册表单</h3></div><button className="text-action" type="button">打开注册表单</button><div className="field-table" role="table"><div className="field-row field-head" role="row"><span>字段</span><span>说明</span></div>{fields.map(([name, desc]) => <div className="field-row" key={name} role="row"><b>{name}</b><span>{desc}</span></div>)}</div><div className="notice notice-security"><strong>密码安全提醒</strong><p>请勿在公开频道、截图或邮件中发送密码；管理员不会主动索取你的密码。</p></div><ol className="number-list"><li>点击上方“立即注册”打开表单并提交。</li><li>注册成功后，请继续完成安装。</li><li>进入游戏后使用密码完成登录验证。</li></ol></>
}

const officialSteps = ['下载安装包：保存到桌面或下载目录，不要放进 .minecraft。', '完全退出启动器：关闭游戏和官方启动器，并退出托盘程序。', '解压并运行：双击 安装WindRealm.bat，等待显示安装成功。', '选择新配置启动：在 Java 版列表选择“风殿下舰长服 Fabric”。', '进入服务器：打开多人游戏，双击“风殿下舰长服”；首次按 V 设置语音。']
const pclSteps = ['准备 PCL2：登录 Minecraft 账号并保持启动器打开。', '下载整合包：保留 .mrpack 原文件，不要解压。', '拖进 PCL2 窗口：拖放后将自动开始安装。', '等待下载完成：无需手动安装加载器或模组。', '启动并进入服务器：选择 WindRealm-26.2 后启动游戏。']
function VoicePanel({ type }: { type: 'official' | 'pcl' }) { const official = type === 'official'; const steps = official ? officialSteps : pclSteps; return <section className="voice-method-panel" role="tabpanel"><div className="voice-method-title"><span>{official ? 'WINDOWS · Minecraft Launcher' : 'THIRD-PARTY LAUNCHER · PCL2'}</span><h4>{official ? '官方启动器：一键自动安装' : '第三方启动器：导入整合包'}</h4></div><p className="voice-method-summary">{official ? '自动安装最新正式版 Minecraft、Fabric 和语音模组，创建独立游戏配置并预置服务器。' : '下载整合包后直接拖到 PCL2 窗口，即可安装 Minecraft 和所需组件。'}</p><div className="voice-download-row"><a className="voice-download" download href={resolveContentUrl(official ? 'downloads/WindRealm-official-launcher-installer-windows-v2.0.1.zip' : 'downloads/WindRealm-26.2.mrpack')}>{official ? '下载官方启动器安装包' : '下载 WindRealm 整合包'}</a><small>{official ? 'ZIP 压缩包 · 仅支持 Windows 10 / 11' : '不要解压 · 直接拖进 PCL2 窗口'}</small></div><div className="voice-example-note"><strong>{official ? '不会修改已有游戏版本' : '最适合第三方启动器用户'}</strong><p>{official ? '安装器会创建独立游戏目录和“风殿下舰长服 Fabric”配置。' : '.mrpack 是启动器可直接读取的整合包格式。'}</p></div><Steps>{steps.map((step, index) => <li key={step}><b>{step.split('：')[0]}</b><span>{step.split('：')[1]}</span>{index === 3 && <figure className="docs-screenshot"><img alt={official ? 'Minecraft 官方启动器中已选择风殿下舰长服 Fabric' : 'Minecraft 多人游戏列表中的风殿下舰长服'} src={resolveContentUrl(official ? 'tutorial/official-launcher-select-windrealm.png' : 'tutorial/multiplayer-server-list.png')} /><figcaption>安装完成后，确认配置后即可开始游戏。</figcaption></figure>}</li>)}</Steps><div className="voice-chat-notes"><strong>{official ? '官方启动器常见问题' : '第三方启动器常见问题'}</strong><ul><li>V 无响应时，确认启动的是 Fabric 配置，而不是原版游戏。</li><li>麦克风不可用时，在 Windows 隐私设置中允许麦克风权限并重新选择设备。</li></ul></div></section> }
function Install({ document }: { document: ContentDocument }) {
  const { lead } = splitHeadingBlocks(document.body); const [mode, setMode] = useState<'auto' | 'manual'>('auto'); const [menuOpen, setMenuOpen] = useState(false); const [tab, setTab] = useState<'official' | 'pcl'>('official'); const menu = useRef<HTMLDivElement>(null)
  useEffect(() => { const close = (e: PointerEvent) => { if (!menu.current?.contains(e.target as Node)) setMenuOpen(false) }; const esc = (e: KeyboardEvent) => e.key === 'Escape' && setMenuOpen(false); globalThis.document.addEventListener('pointerdown', close); globalThis.document.addEventListener('keydown', esc); return () => { globalThis.document.removeEventListener('pointerdown', close); globalThis.document.removeEventListener('keydown', esc) } }, [])
  const Heading = ({ automatic }: { automatic: boolean }) => <div className="install-mode-heading"><span>{automatic ? 'AUTOMATIC INSTALL' : 'MANUAL INSTALL'}</span><div className="install-mode-title-row"><h3>{automatic ? '自动安装（推荐）' : '手动安装'}</h3><div className="install-mode-menu" ref={menu}><button aria-expanded={menuOpen} aria-haspopup="menu" aria-label="切换安装方式" className="install-mode-menu-trigger" type="button" onClick={() => setMenuOpen(!menuOpen)}><span /></button>{menuOpen && <div className="install-mode-menu-popover" role="menu"><button aria-checked={mode === 'auto'} role="menuitemradio" type="button" onClick={() => { setMode('auto'); setMenuOpen(false) }}><span><strong>自动安装</strong><small>推荐，新手直接选择</small></span><i>{mode === 'auto' ? '✓' : ''}</i></button><button aria-checked={mode === 'manual'} role="menuitemradio" type="button" onClick={() => { setMode('manual'); setMenuOpen(false) }}><span><strong>手动安装</strong><small>已有游戏环境时使用</small></span><i>{mode === 'manual' ? '✓' : ''}</i></button></div>}</div></div></div>
  return <><Markdown components={{ p: ({ children }) => <p className="lead">{children}</p> }}>{lead}</Markdown><section className="install-mode-panel" hidden={mode !== 'auto'} id="install-auto-panel"><Heading automatic /><div className="install-mode-body"><p>自动准备进入舰长服所需的游戏环境和语音模组。根据你使用的启动器选择一种方法即可，不要混用两个安装包。</p><div aria-label="选择自动安装方式" className="voice-method-tabs" role="tablist"><button aria-controls="voice-official-panel" aria-selected={tab === 'official'} className="voice-method-tab" id="voice-official-tab" role="tab" type="button" onClick={() => setTab('official')}>官方启动器<small>只适用于有正版的玩家</small></button><button aria-controls="voice-pcl-panel" aria-selected={tab === 'pcl'} className="voice-method-tab" id="voice-pcl-tab" role="tab" type="button" onClick={() => setTab('pcl')}>第三方启动器<small>推荐，适用于正版或离线登录</small></button></div>{tab === 'official' ? <VoicePanel type="official" /> : <VoicePanel type="pcl" />}</div></section><section className="install-mode-panel manual-install-panel" hidden={mode !== 'manual'} id="install-manual-panel"><Heading automatic={false} /><div className="install-mode-body"><p>已经有 Minecraft Java 版时，可以直接手动添加服务器进入。游戏内语音是可选功能。</p><details className="version-guide compact-version-guide"><summary className="compact-version-guide-head">版本兼容性提示：旧版本可以进服，但可能存在显示和交互限制</summary><div className="version-guide-body"><p>Java 1.7 及以上可进入服务器；低版本客户端可能无法显示新方块、物品或机制。</p><div className="known-issues"><div className="known-issues-copy"><small>JAVA 1.7–1.16.5</small><strong>已知限制</strong></div><div className="known-issues-body"><ul><li><b>世界高度</b><span>可能无法看见或交互新版世界高度区域。</span></li><li><b>背包同步</b><span>部分新物品可能显示不完整。</span></li></ul></div></div></div></details><section className="manual-server-guide"><div className="voice-method-title"><span>MULTIPLAYER · MANUAL SETUP</span><h4>手动添加服务器</h4></div><p className="voice-method-summary">不安装任何模组也可以进入服务器。</p><Steps>{['准备 Java 版游戏', '启动一次游戏', '打开添加服务器', '填写服务器信息', '进入服务器'].map((step, i) => <li key={step}><b>{step}</b><span>{i === 3 ? '服务器名称：风殿下舰长服；服务器地址：windking.fans。' : '按游戏中的提示完成此步骤。'}</span></li>)}</Steps></section><details className="manual-voice-guide"><summary className="manual-voice-summary"><span>可选：手动安装游戏内语音</span><small>Fabric + Simple Voice Chat</small></summary><div className="manual-voice-body"><p>语音模组不是进服必需，但所有版本必须互相匹配。</p><Steps>{['选择游戏版本', '安装 Fabric Loader', '启动 Fabric 一次后退出', '下载 Fabric API', '下载 Simple Voice Chat', '将模组放入 mods 文件夹', '启动 Fabric 并按 V 测试语音'].map((step) => <li key={step}><b>{step}</b><span>请使用与游戏版本对应的 Fabric 模组文件。</span></li>)}</Steps><div className="voice-chat-links"><a href="https://docs.fabricmc.net/zh_cn/players/installing-fabric/windows" rel="noreferrer" target="_blank">Fabric 官方 Windows 教程 ↗</a><a href="https://modrinth.com/mod/fabric-api" rel="noreferrer" target="_blank">下载 Fabric API ↗</a><a href="https://modrinth.com/plugin/simple-voice-chat" rel="noreferrer" target="_blank">下载 Simple Voice Chat ↗</a></div></div></details></div></section></>
}

function Login({ document }: { document: ContentDocument }) { const { lead, blocks } = splitHeadingBlocks(document.body); return <><Markdown components={{ p: ({ children }) => <p className="lead">{children}</p> }}>{lead}</Markdown><div className="auth-state-note"><strong>登录状态说明</strong><p>进入服务器后，完成验证才可以正常游玩。</p></div>{blocks.map((block, index) => <section className={index === 1 ? 'login-method login-method-command' : 'login-method'} key={block.title}><div className="method-heading"><span>登录方式 {index + 1}</span><h3>{block.title}</h3></div><Markdown components={{ p: ({ children }) => <p>{children}</p>, pre: ({ children }) => <pre className="command-box">{children}</pre>, img: ({ src = '', alt = '' }) => <figure className="login-screen"><img alt={alt} src={resolveContentUrl(src)} /><figcaption>{alt}</figcaption></figure>, blockquote: ({ children }) => <div className="auth-state-note">{children}</div> }}>{block.content}</Markdown>{index === 0 ? <p className="success-line"><span>登录成功</span>验证完成后即可正常开始游戏。</p> : <><ul className="plain-list"><li>按 <kbd>T</kbd> 打开聊天栏，再输入命令。</li><li>重新进入服务器时通常仍需要登录。</li></ul><p className="authme-reference">需要更多帮助？<a href="https://wiki.helpch.at/clips-plugins/authme-reloaded" rel="noreferrer" target="_blank">查看 AuthMe Wiki ↗</a></p></>}</section>)}</> }
function Faq({ document }: { document: ContentDocument }) { const { blocks } = splitHeadingBlocks(document.body); return <>{blocks.map((block, i) => <details key={block.title}><summary>{block.title}</summary><Markdown components={{ p: ({ children }) => <p>{children}{i === 2 && <span className="server-hours-note">服务器开放时间以状态页与群公告为准。</span>}</p> }}>{block.content}</Markdown></details>)}</> }
export function GuideBlocks({ document }: { document: ContentDocument }) { if (document.layout === 'register') return <Register document={document} />; if (document.layout === 'install') return <Install document={document} />; if (document.layout === 'login') return <Login document={document} />; return <Faq document={document} /> }
